/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;

/**
 *
 * @author pc
 */
public class FormVendedor extends javax.swing.JFrame {

    /**
     * Creates new form FormVendedor
     */
    public FormVendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCLi = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuProd = new javax.swing.JMenuItem();
        menuVend = new javax.swing.JMenu();
        menuPaga = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 500));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setText("Clientes");

        menuCLi.setText("Cliente");
        menuCLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCLiActionPerformed(evt);
            }
        });
        jMenu1.add(menuCLi);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Produtos");

        menuProd.setText("Produto");
        menuProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdActionPerformed(evt);
            }
        });
        jMenu2.add(menuProd);

        jMenuBar1.add(jMenu2);

        menuVend.setText("Vendas");
        menuVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendActionPerformed(evt);
            }
        });

        menuPaga.setText("Pagamento");
        menuPaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPagaActionPerformed(evt);
            }
        });
        menuVend.add(menuPaga);

        jMenuBar1.add(menuVend);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCLiActionPerformed
        // TODO add your handling code here:
        FormClientes telaCliente = new FormClientes();
        telaCliente.setVisible(true);
    }//GEN-LAST:event_menuCLiActionPerformed

    private void menuProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdActionPerformed
        // TODO add your handling code here:
        FormProdutos telaProd = new FormProdutos();
        telaProd.setVisible(true);
    }//GEN-LAST:event_menuProdActionPerformed

    private void menuVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuVendActionPerformed

    private void menuPagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPagaActionPerformed
        // TODO add your handling code here:        
        FormVendas telaVenda = new FormVendas();
        telaVenda.setVisible(true);
    }//GEN-LAST:event_menuPagaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCLi;
    private javax.swing.JMenuItem menuPaga;
    private javax.swing.JMenuItem menuProd;
    private javax.swing.JMenu menuVend;
    // End of variables declaration//GEN-END:variables
}
